source 'https://rubygems.org'

gem 'docker-api', require: 'docker'
gem 'httparty'

gem 'cucumber'
gem 'rspec-expectations'
gem 'excon', '~> 0.71.0' # 0.50.1 raises an uninitialized constant Excon::Errors::InternalServerError
